name: Spigot Event List
title: Spigot Event List
theme: jekyll-theme-primer
lang: ja
twitter:
  username: fly_in_pig
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /image/logo.png
        height: 630
        width: 1200
exclude:
  - .idea
  - node_modules
  - src
  - template
  - vendor
  - .eslintrc.json
  - .gitignore
  - _config.yml
  - events.yaml
  - exclude-events.yaml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - package-lock.json
  - spigot-event-list.iml
  - tsconfig.json